# -*- coding: utf-8 -*-
"""SuperStore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RTF2MCGL9UFGCiNkNi0P4W6t3MpSQ3f2
"""

import numpy as np
import pandas as pd

df=pd.read_csv('/content/drive/MyDrive/EDA-Skill/Ecommerce_Order_Test_Dataset.csv')

df.head(5)

print(df.shape)

print(df.columns)

df.info()

df.describe()

df.isnull().sum()

updated_df=df
updated_df["City"]=updated_df["City"].fillna("unknown")
updated_df["Customer_Name"]=updated_df["Customer_Name"].fillna("unknown")

updated_df["Rating"]=updated_df["Rating"].fillna(updated_df["Rating"].mean())

updated_df["Payment_Mode"]=updated_df["Payment_Mode"].fillna("unknown")

